"""Build DMFC neural tensors from DANDI 000130.  [FOUNDATION -> plan 1.D]

Runs in the ISOLATED ingestion env (dandi/pynwb/nlb_tools); writes plain numpy
tensors to ``data/processed/`` that the modeling env reads. Modeling code never
imports pynwb/dandi. The heavy stack (nlb_tools/dandi/pynwb) is imported LAZILY
inside the I/O functions, so this module imports fine in the modeling/contracts env
too (numpy + the torch-free ``src.conditions`` / ``src.training.config`` only).

Verified dataset facts (NLB DMFC_RSG): 1 monkey (H), 1 session, 54 sorted units
(40 held-in / 14 held-out -- we use ALL 54, not the NLB forecasting split), ~1,289
trials, events Ready/Set/Go, behavioral tp. 40 real conditions = prior 2 x ts 5 x
effector 2 x direction 2; we MARGINALIZE the 2 target directions -> the 20-condition
comparison set (prior x ts x effector), matching ``src.conditions``.

OUTPUTS (into ``out_dir``, default ``data/processed/``)
    dmfc_rsg.npy         states  [20, T, U]   condition-averaged rates, U=54.
    dmfc_inputs.npy      inputs  [20, T, 3]   external drive, model's 3-channel encoding.
    dmfc_rsg_splits.npy  splits  [S, 20, T, U] disjoint trial halves -> RSA noise ceiling.
    dmfc_meta.json       provenance: per-cond trial counts, mean tp, event bins, pins.

ALIGNMENT (decision: match the model's fixed canvas). Each trial is aligned to Ready
and placed on the model's fixed ``total_time`` canvas at ``bin_ms`` bins, Ready fixed
at ``round(ready_onset/bin_ms)``. So T == round(total_time/bin_ms) is uniform across
conditions and Ready/Set land at the SAME fractional positions as the model after the
shared ``preprocess`` resample. The 3-channel input rep is generated by the model's
OWN ``src.task.rsg.build_trial`` (same constants + scale), so ``idsa.input_dsa``'s
shared-input-dim/scale requirement holds by construction.

VERIFY ON LOAD (do not assume): ts values and effector labels match src.conditions;
both effectors and both priors present; per-cell trial counts logged; thin cells
flagged. Exact ``trial_info`` column names/units are DISCOVERED and asserted here.
"""

from __future__ import annotations

import json
import logging
import subprocess
from dataclasses import replace
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from src.conditions import (
    CONDITIONS,
    EFFECTORS,
    N_CONDITIONS,
    PRIORS,
    TS_BY_PRIOR,
    Condition,
    condition_index,
)
from src.training.config import Config

log = logging.getLogger("build_neural")

PROCESSED_DIR = Path("data/processed")
DANDISET_ID = "000130"

# Neural preprocessing defaults (all exposed via the CLI).
DEFAULT_BIN_MS = 20
DEFAULT_SMOOTH_MS = 40
N_SPLITS = 2

# Candidate ``trial_info`` column names, tried in order. DMFC_RSG's exact names are
# asserted at load (AGENTS "verify on load"); extend these lists if a load fails
# with an "expected one of" error naming the columns actually present.
_COL_CANDIDATES: Dict[str, List[str]] = {
    "effector": ["is_eye", "effector", "is_saccade"],
    "prior": ["is_short", "prior", "is_short_block", "gain"],
    "ts": ["t_s", "ts", "sample_interval"],
    "tp": ["t_p", "tp", "produced_interval"],
    "direction": ["theta", "target_dir", "direction", "is_right"],
    "ready": ["ready_time", "ready"],
    "set": ["set_time", "set"],
    "go": ["go_time", "go", "move_onset_time", "response_time"],
    "outlier": ["is_outlier", "outlier"],
}


# ---------------------------------------------------------------------------
# Pure numpy/pandas core (testable WITHOUT nlb_tools or a download)
# ---------------------------------------------------------------------------


def canvas_len(cfg: Config, bin_ms: float) -> int:
    """Number of neural time bins = the model's fixed canvas at ``bin_ms`` resolution."""
    return int(round(cfg.total_time / bin_ms))


def _pick_column(columns: Sequence[str], key: str, required: bool = True) -> Optional[str]:
    """Resolve a logical field (e.g. ``prior``) to the real column present in the data."""
    for cand in _COL_CANDIDATES[key]:
        if cand in columns:
            return cand
    if required:
        raise KeyError(
            f"could not find a {key!r} column; tried {_COL_CANDIDATES[key]}; "
            f"trial_info has {list(columns)}. Add the real name to _COL_CANDIDATES."
        )
    return None


def _col_ms(df, name: str) -> np.ndarray:
    """Return column ``name`` as float milliseconds, handling timedelta or s/ms numerics."""
    s = df[name].to_numpy()
    if np.issubdtype(s.dtype, np.timedelta64):
        return s / np.timedelta64(1, "ms")
    s = s.astype(float)
    finite = s[np.isfinite(s)]
    if finite.size and np.nanmax(np.abs(finite)) < 10.0:  # values look like seconds
        s = s * 1000.0
    return s


def _label_effector(df, col: str) -> np.ndarray:
    """Map the effector column to canonical 'eye'/'hand' strings."""
    vals = df[col].to_numpy()
    if col in ("is_eye", "is_saccade"):
        return np.where(vals.astype(bool), "eye", "hand")
    out = np.array([str(v).lower() for v in vals], dtype=object)
    # Accept already-canonical or common synonyms.
    synonym = {"saccade": "eye", "eye": "eye", "hand": "hand", "joystick": "hand"}
    return np.array([synonym.get(v, v) for v in out], dtype=object)


def _label_prior(df, col: str) -> np.ndarray:
    """Map the prior column to canonical 'short'/'long' strings."""
    vals = df[col].to_numpy()
    if col in ("is_short", "is_short_block"):
        return np.where(vals.astype(bool), "short", "long")
    out = np.array([str(v).lower() for v in vals], dtype=object)
    synonym = {"short": "short", "long": "long", "0": "short", "1": "long"}
    return np.array([synonym.get(v, v) for v in out], dtype=object)


def resolve_trials(trial_info) -> Dict[str, np.ndarray]:
    """Normalize a raw ``trial_info`` DataFrame into per-trial arrays + a valid mask.

    Pure (no nlb_tools). Returns a dict with, per trial: ``cond_idx`` (canonical 0..19
    or -1 if invalid), ``direction`` (int label), ``tp`` (ms), and ``keep`` (bool mask
    of trials that map to a real Condition). Verifies ts/effector/prior against
    ``src.conditions`` and raises if the schema does not line up.
    """
    cols = list(trial_info.columns)
    c_eff = _pick_column(cols, "effector")
    c_prior = _pick_column(cols, "prior")
    c_ts = _pick_column(cols, "ts")
    c_tp = _pick_column(cols, "tp")
    c_dir = _pick_column(cols, "direction", required=False)
    c_out = _pick_column(cols, "outlier", required=False)

    effector = _label_effector(trial_info, c_eff)
    prior = _label_prior(trial_info, c_prior)
    ts_ms = _col_ms(trial_info, c_ts)
    tp_ms = _col_ms(trial_info, c_tp)
    n = len(effector)

    if c_dir is not None:
        raw_dir = trial_info[c_dir].to_numpy()
        _, direction = np.unique(raw_dir, return_inverse=True)  # 0..(D-1)
    else:
        log.warning("no direction column found; treating all trials as one direction")
        direction = np.zeros(n, dtype=int)

    outlier = (
        trial_info[c_out].to_numpy().astype(bool)
        if c_out is not None
        else np.zeros(n, dtype=bool)
    )

    cond_idx = np.full(n, -1, dtype=int)
    for i in range(n):
        if outlier[i] or not np.isfinite(ts_ms[i]):
            continue
        try:
            cond = Condition(str(prior[i]), int(round(ts_ms[i])), str(effector[i]))
        except ValueError:
            continue  # (prior, ts, effector) not a real cell (e.g. aborted trial)
        cond_idx[i] = condition_index(cond)

    keep = cond_idx >= 0
    _verify_schema(prior[keep], ts_ms[keep], effector[keep])
    log.info("resolved %d/%d trials into %d conditions", int(keep.sum()), n, N_CONDITIONS)
    return {"cond_idx": cond_idx, "direction": direction, "tp": tp_ms, "keep": keep}


def _verify_schema(prior: np.ndarray, ts_ms: np.ndarray, effector: np.ndarray) -> None:
    """Assert the resolved labels match ``src.conditions`` (fail loud, fail early)."""
    got_eff = set(map(str, effector))
    if not got_eff <= set(EFFECTORS) or not set(EFFECTORS) <= got_eff:
        raise ValueError(f"effector labels {got_eff} != schema {set(EFFECTORS)}")
    got_priors = set(map(str, prior))
    if not set(PRIORS) <= got_priors:
        raise ValueError(f"missing a prior: got {got_priors}, need {set(PRIORS)}")
    for p in PRIORS:
        sel = prior == p
        got_ts = set(int(round(v)) for v in ts_ms[sel])
        if not got_ts <= set(TS_BY_PRIOR[p]):
            raise ValueError(
                f"{p} prior has ts {sorted(got_ts)} outside schema {TS_BY_PRIOR[p]}"
            )


def _fill_time_nans(states: np.ndarray) -> np.ndarray:
    """Forward/back-fill NaN bins along time per (condition, unit) so output is finite.

    Late tail bins can be all-NaN when no trial in a condition reached that far; hold
    the last observed rate forward (and back-fill any leading gap) rather than emit NaN,
    which the preprocessor rejects.
    """
    out = np.array(states, dtype=float)
    n_cond, T, U = out.shape
    for c in range(n_cond):
        for u in range(U):
            col = out[c, :, u]
            finite = np.where(np.isfinite(col))[0]
            if finite.size == 0:
                col[:] = 0.0
                continue
            first, last = finite[0], finite[-1]
            col[:first] = col[first]
            col[last + 1:] = col[last]
            # interior gaps: linear interp over the finite support
            if finite.size < (last - first + 1):
                idx = np.arange(first, last + 1)
                col[first:last + 1] = np.interp(idx, finite, col[finite])
            out[c, :, u] = col
    return out


def average_conditions(
    arrays: Sequence[np.ndarray],
    cond_idx: np.ndarray,
    direction: np.ndarray,
    indices: Sequence[int],
) -> np.ndarray:
    """Direction-balanced condition average over the given trial ``indices``.

    Pure numpy. ``arrays[i]`` is a per-trial ``[T, U]`` rate array (may contain NaN from
    out-of-range bins). For each canonical condition we average within each target
    direction first, then average the direction-means -> marginalizing direction with
    equal weight (robust to the sampled prior's direction imbalance). Returns
    ``[20, T, U]``, NaN-filled to finite.
    """
    T, U = np.asarray(arrays[0]).shape
    out = np.full((N_CONDITIONS, T, U), np.nan, dtype=float)
    idx = np.asarray(indices)
    for c in range(N_CONDITIONS):
        in_c = idx[cond_idx[idx] == c]
        if in_c.size == 0:
            continue
        dir_means = []
        for d in np.unique(direction[in_c]):
            in_cd = in_c[direction[in_c] == d]
            stack = np.stack([np.asarray(arrays[i], dtype=float) for i in in_cd], axis=0)
            dir_means.append(np.nanmean(stack, axis=0))
        out[c] = np.nanmean(np.stack(dir_means, axis=0), axis=0)
    return _fill_time_nans(out)


def stratified_splits(
    cond_idx: np.ndarray, indices: Sequence[int], n_splits: int, rng: np.random.Generator
) -> List[np.ndarray]:
    """Partition trial ``indices`` into ``n_splits`` disjoint sets, stratified by condition.

    Stratifying by condition keeps every condition populated in every split, so each
    split's condition-average (the RSA noise-ceiling input) is well-defined.
    """
    parts: List[List[int]] = [[] for _ in range(n_splits)]
    idx = np.asarray(indices)
    for c in range(N_CONDITIONS):
        in_c = idx[cond_idx[idx] == c]
        in_c = rng.permutation(in_c)
        for s, chunk in enumerate(np.array_split(in_c, n_splits)):
            parts[s].extend(chunk.tolist())
    return [np.asarray(sorted(p)) for p in parts]


def build_input_tensor(cfg: Config, bin_ms: float) -> np.ndarray:
    """The 3-channel external drive [20, T, 3] on the neural canvas.

    Reuses the model's OWN generator so the encoding + scale are identical to the
    stored model inputs (Ready/Set pulses on ch0, tonic prior/effector context on
    ch1/ch2), which is what ``idsa.input_dsa`` requires (matching input dim & scale).
    """
    from src.task.rsg import build_trial

    ncfg = replace(cfg, dt=float(bin_ms))
    inp = np.stack([build_trial(ncfg, c, jitter=False)[0][0] for c in CONDITIONS], axis=0)
    return inp.astype(float)


def condition_event_bins(cfg: Config, bin_ms: float, mean_tp_ms: Dict[str, float]) -> Dict:
    """Per-condition Ready/Set/Go bin indices for the future event_anchored warp."""
    ready = int(round(cfg.ready_onset / bin_ms))
    out = {}
    T = canvas_len(cfg, bin_ms)
    for c in CONDITIONS:
        set_bin = ready + int(round(c.ts / bin_ms))
        tp = mean_tp_ms.get(c.key, float(c.ts))
        go_bin = min(T - 1, ready + int(round((c.ts + tp) / bin_ms)))
        out[c.key] = {"ready": ready, "set": set_bin, "go": go_bin}
    return out


def verify_neural_tensors(
    states: np.ndarray, inputs: np.ndarray, splits: np.ndarray
) -> None:
    """Assert the emitted tensors satisfy the downstream contract; raise on any breach."""
    if states.shape[0] != N_CONDITIONS:
        raise ValueError(f"states must have {N_CONDITIONS} conditions, got {states.shape}")
    if inputs.shape[0] != N_CONDITIONS or inputs.shape[2] != 3:
        raise ValueError(f"inputs must be [20, T, 3], got {inputs.shape}")
    if states.shape[1] != inputs.shape[1]:
        raise ValueError(
            f"states/inputs must share the time axis: {states.shape[1]} != {inputs.shape[1]}"
        )
    if not np.isfinite(states).all() or not np.isfinite(inputs).all():
        raise ValueError("states/inputs contain non-finite values")
    splits = np.asarray(splits)
    if splits.ndim != 4 or splits.shape[1] != N_CONDITIONS or splits.shape[0] < 2:
        raise ValueError(f"splits must be [S>=2, 20, T, U], got {splits.shape}")
    if not np.isfinite(splits).all():
        raise ValueError("splits contain non-finite values")
    log.info(
        "verify OK: states%s inputs%s splits%s all finite",
        states.shape, inputs.shape, splits.shape,
    )


# ---------------------------------------------------------------------------
# nlb_tools / dandi I/O (thin; only runs in the ingestion env with real data)
# ---------------------------------------------------------------------------


def _ensure_download(dandiset_id: str, download_dir: Path) -> Path:
    """Download the dandiset if absent; return the path to its NWB file."""
    download_dir.mkdir(parents=True, exist_ok=True)
    existing = sorted(download_dir.glob(f"{dandiset_id}/**/*.nwb"))
    if not existing:
        log.info("downloading DANDI:%s into %s", dandiset_id, download_dir)
        subprocess.run(
            ["dandi", "download", f"DANDI:{dandiset_id}"],
            cwd=str(download_dir), check=True,
        )
        existing = sorted(download_dir.glob(f"{dandiset_id}/**/*.nwb"))
    if not existing:
        raise FileNotFoundError(f"no .nwb found under {download_dir}/{dandiset_id}")
    # Prefer the NLB 'train' file: the 'test' file has withheld/NaN-masked data (units
    # and behavioral tp are held out for the competition), which we do not want here.
    train = [p for p in existing if "train" in p.name.lower()]
    chosen = train[0] if train else existing[0]
    log.info("using NWB file %s", chosen)
    return chosen


def _load_rates(nwb_path: Path, bin_ms: float, smooth_ms: float):
    """Load the NWB, rebin to ``bin_ms``, Gaussian-smooth -> (dataset, rate_field, unit_cols).

    ``split_heldout=False`` keeps all 54 units in one 'spikes' field (we are not doing
    the NLB held-in/held-out forecasting split).
    """
    from nlb_tools.nwb_interface import NWBDataset

    dataset = NWBDataset(str(nwb_path), split_heldout=False)
    dataset.resample(int(bin_ms))
    # parallelized=False: macOS multiprocessing spin-up is slow/fragile and we want a
    # deterministic single-process path (AGENTS "no interactive-only assumptions").
    dataset.smooth_spk(smooth_ms, signal_type="spikes", name="smth", parallelized=False)
    rate_field = "spikes_smth"
    unit_cols = list(dataset.data[rate_field].columns)
    log.info("loaded %d units; binned to %d ms, smoothed %g ms", len(unit_cols), bin_ms, smooth_ms)
    return dataset, rate_field, unit_cols


def _aligned_trial_arrays(
    dataset, rate_field: str, ready_col: str, cfg: Config, bin_ms: float, trial_info
) -> Tuple[List[np.ndarray], np.ndarray]:
    """Ready-aligned per-trial rate arrays on the fixed canvas, ROW-ALIGNED to trial_info.

    Uses ``make_trial_data`` with the model's canvas window ``(-ready_onset,
    total_time - ready_onset)`` so every trial yields exactly ``T = canvas_len`` bins,
    reindexed onto the align-time grid (out-of-range bins -> NaN). ``make_trial_data``
    drops some trials (overlap/no-data), so we key arrays by ``trial_id`` and return a
    list positionally aligned to ``trial_info`` rows plus a ``has_data`` mask -- the
    callers index arrays by trial_info row exactly like ``cond_idx``/``direction``.
    """
    T = canvas_len(cfg, bin_ms)
    lo = -cfg.ready_onset
    # make_trial_data adds the range to the align_field timedelta, so the offsets must
    # be timedelta64 (not float ms).
    lo_td = np.timedelta64(int(round(lo)), "ms")
    hi_td = np.timedelta64(int(round(cfg.total_time - cfg.ready_onset)), "ms")
    td = dataset.make_trial_data(
        align_field=ready_col, align_range=(lo_td, hi_td), allow_nans=True,
    )
    align_ms = (td["align_time"] / np.timedelta64(1, "ms")).to_numpy()
    bin_idx = np.round((align_ms - lo) / bin_ms).astype(int)
    rates = td[rate_field].to_numpy(dtype=float)  # [rows, U]
    U = rates.shape[1]

    by_tid: Dict[int, np.ndarray] = {}
    for tid, grp in td.groupby("trial_id").indices.items():
        rows = np.asarray(grp)
        canvas = np.full((T, U), np.nan, dtype=float)
        b = bin_idx[rows]
        ok = (b >= 0) & (b < T)
        canvas[b[ok]] = rates[rows][ok]
        by_tid[int(tid)] = canvas

    tids = trial_info["trial_id"].to_numpy()
    arrays: List[np.ndarray] = []
    has_data = np.zeros(len(tids), dtype=bool)
    for i, tid in enumerate(tids):
        canvas = by_tid.get(int(tid))
        if canvas is None:
            arrays.append(np.full((T, U), np.nan, dtype=float))
        else:
            arrays.append(canvas)
            has_data[i] = True
    return arrays, has_data


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def build_neural(
    out_dir: Path = PROCESSED_DIR,
    download_dir: Path = Path("data/raw"),
    dandiset_id: str = DANDISET_ID,
    bin_ms: float = DEFAULT_BIN_MS,
    smooth_ms: float = DEFAULT_SMOOTH_MS,
    config: Optional[Config] = None,
    n_splits: int = N_SPLITS,
    seed: int = 0,
) -> None:
    """Ingest DMFC_RSG -> data/processed/. Lazy-imports the ingestion stack."""
    try:
        import nlb_tools  # noqa: F401
    except ImportError as e:
        raise ImportError(
            "build_neural needs the ingestion env (nlb_tools/dandi/pynwb). "
            "See requirements-ingestion.txt."
        ) from e

    cfg = config or Config()
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)

    nwb_path = _ensure_download(dandiset_id, Path(download_dir))
    dataset, rate_field, unit_cols = _load_rates(nwb_path, bin_ms, smooth_ms)

    trials = resolve_trials(dataset.trial_info)
    ready_col = _pick_column(list(dataset.trial_info.columns), "ready")
    arrays, has_data = _aligned_trial_arrays(
        dataset, rate_field, ready_col, cfg, bin_ms, dataset.trial_info
    )

    keep = np.where(trials["keep"] & has_data)[0]
    cond_idx, direction, tp = trials["cond_idx"], trials["direction"], trials["tp"]

    states = average_conditions(arrays, cond_idx, direction, keep)
    split_idx = stratified_splits(cond_idx, keep, n_splits, rng)
    splits = np.stack(
        [average_conditions(arrays, cond_idx, direction, s) for s in split_idx], axis=0
    )
    inputs = build_input_tensor(cfg, bin_ms)

    verify_neural_tensors(states, inputs, splits)

    counts = {c.key: int((cond_idx[keep] == condition_index(c)).sum()) for c in CONDITIONS}
    mean_tp = {
        c.key: float(np.nanmean(tp[keep][cond_idx[keep] == condition_index(c)]))
        for c in CONDITIONS
    }
    _log_counts(counts)

    np.save(out_dir / "dmfc_rsg.npy", states)
    np.save(out_dir / "dmfc_inputs.npy", inputs)
    np.save(out_dir / "dmfc_rsg_splits.npy", splits)
    _write_meta(out_dir, cfg, bin_ms, smooth_ms, unit_cols, counts, mean_tp, nwb_path)
    log.info("wrote dmfc_rsg / dmfc_inputs / dmfc_rsg_splits / dmfc_meta to %s", out_dir)


def _log_counts(counts: Dict[str, int], thin: int = 5) -> None:
    total = sum(counts.values())
    thin_cells = {k: v for k, v in counts.items() if v < thin}
    log.info("per-condition trial counts (total %d): %s", total, counts)
    if thin_cells:
        log.warning("THIN cells (< %d trials): %s -- flagged, not dropped", thin, thin_cells)


def _git_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], text=True
        ).strip()
    except Exception:
        return "unknown"


def _write_meta(
    out_dir: Path, cfg: Config, bin_ms: float, smooth_ms: float,
    unit_cols, counts: Dict[str, int], mean_tp: Dict[str, float], nwb_path: Path,
) -> None:
    meta = {
        "dandiset": DANDISET_ID,
        "nwb_file": str(nwb_path.name),
        "n_units": len(unit_cols),
        "bin_ms": bin_ms,
        "smooth_ms": smooth_ms,
        "canvas_bins": canvas_len(cfg, bin_ms),
        "total_time_ms": cfg.total_time,
        "ready_onset_ms": cfg.ready_onset,
        "alignment": "ready-aligned on the model's fixed total_time canvas",
        "direction_marginalized": True,
        "trial_counts": counts,
        "mean_tp_ms": mean_tp,
        "event_bins": condition_event_bins(cfg, bin_ms, mean_tp),
        "git_sha": _git_sha(),
    }
    (out_dir / "dmfc_meta.json").write_text(json.dumps(meta, indent=2, sort_keys=True))


# ---------------------------------------------------------------------------
# Entry point (same interactively or under SLURM; no cluster values baked in)
# ---------------------------------------------------------------------------


def main(argv=None) -> int:
    import argparse

    logging.basicConfig(level=logging.INFO, format="[%(name)s] %(message)s")
    p = argparse.ArgumentParser(description="Build DMFC neural tensors from DANDI 000130.")
    p.add_argument("--out-dir", type=str, default=str(PROCESSED_DIR))
    p.add_argument("--download-dir", type=str, default="data/raw")
    p.add_argument("--dandiset-id", type=str, default=DANDISET_ID)
    p.add_argument("--bin-ms", type=float, default=DEFAULT_BIN_MS)
    p.add_argument("--smooth-ms", type=float, default=DEFAULT_SMOOTH_MS)
    p.add_argument("--n-splits", type=int, default=N_SPLITS)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--config", type=str, default=None, help="optional Config YAML (channel encodings)")
    args = p.parse_args(argv)

    cfg = Config.from_yaml(args.config) if args.config else Config()
    build_neural(
        out_dir=Path(args.out_dir),
        download_dir=Path(args.download_dir),
        dandiset_id=args.dandiset_id,
        bin_ms=args.bin_ms,
        smooth_ms=args.smooth_ms,
        config=cfg,
        n_splits=args.n_splits,
        seed=args.seed,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
